### ISSUE TITLE
this maybe is not an issue, but...

### ISSUE THREAD

**Issue by modder97** [wacossusca34/Consoles#7]
hi can you give support for multiverse?

the plugin works great and everything is fine, but than I start up the server secound time or third time and so on.
The server console gives this warning message for every world it loads up.

(edit by Jarcode): [server logs](http://pastebin.com/raw.php?i=ayiLe7TH)

I can say that, the maps works fine and everything else, but I'm wondering about the warnings, for each world.

Maybe multiversecore dependence should work.

**Comment by modder97** [comment]
the server console doesn't gives errors on first time, but secound and third...
they gives these two warnings.

**Comment by wacossusca34** [comment]
Yeah, and you're right about it having something to do with multiverse. For some reason world load events through other plugins can sometimes cause Consoles to not be able to listen for world load events properly, resulting in null map data stores.

The problem wasn't actually anything severe, though - I have failsafe checks to instantiate data stores if they don't exist (and need to). This error pops up when saving if the world has no map data.

I fixed it in the latest version, the commit that has the fix _should_ be in the `1.6b-beta` build on spigotmc. Let me know if it fixes it.

**Comment by modder97** [comment]
I tried the 1.6b build and I did a clean install, but the problem is still there.
For me The consoles load up before multiverse, I think thats the key.

**Comment by modder97** [comment]
so maybe in plugin.yml we can try, depend: [Multiverse-core]

**Comment by modder97** [comment]
witht depend, the plugin will wait until multiverse is finnished

**Comment by wacossusca34** [comment]
Consoles loads in a very unique way (it loads itself with its own plugin loader on startup). I might have not gotten the commit in the `1.6b-beta` version, I'll have `1.7-beta` out today with some new features and hopefully your issue fixed :)

**Comment by modder97** [comment]
you can always try,
loadbefore: [Multiverse-Core]
in the plugin yml

loadbefore will let Multiverse-Core to load up before the consoles plugin.

**Comment by modder97** [comment]
ok I understand

**Comment by wacossusca34** [comment]
Unfortunately I cannot, the `Consoles` plugin class itself is loaded by `ConsolesLoader` for class instrumentation. See the source code.

**Comment by modder97** [comment]
ok.

**Comment by wacossusca34** [comment]
Should be fixed in the latest update. Does it fix your issue?
